library(datawsets)
library(datasets)
plot(hh+power_consumpt1$Global_active_power)
plot(hh_power_consumpt1$Global_active_power)
hh_power_consumpt <- read.table("C:/Users/m0banks/Downloads/Coursera Videos/Exploratory Data Analysis/exdata-data-household_power_consumption/household_power_consumption.txt", header=TRUE, sep=";", na.string="?")
hh_power_consumpt1 <- hh_power_consumpt[ which(hh_power_consumpt$Date == "1/2/2007" | hh_power_consumpt$Date == "2/2/2007"), ]
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
plot(hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
axis.Date(1, at=hh_power_consumpt1$dateT, labels=format(hh_power_consumpt1$dateT, "%b-%d"), las=2)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, xaxt="n")
dateTime = as.Date(strptime(hh_power_consumpt1$dateT, "%d/%m/%Y%H:%M:%S"))
dateTime = as.Date(strptime(hh_power_consumpt1$dateT, "%Y-%m-%dT%H:%M:%S"))
plot(hh_power_consumpt1$dateTime, hh_power_consumpt1$Sub_metering_1, xaxt="n")
hh_power_consumpt1$dateTime = as.Date(strptime(hh_power_consumpt1$dateT, "%Y-%m-%dT%H:%M:%S"))
hh_power_consumpt1$dateTime <- as.Date(strptime(hh_power_consumpt1$dateT, "%Y-%m-%dT%H:%M:%S"))
hh_power_consumpt1$dateTime = as.Date(strptime(hh_power_consumpt1$dateT, "%d/%m/%Y%H:%M:%S"))
View(hh_power_consumpt1)
hh_power_consumpt1$dateT <- as.POSIXct(paste(as.character(hh_power_consumpt1$Date), as.character(hh_power_consumpt1$Time)), format='%d/%m/%Y %H:%M:%S', tz="GMT")
hh_power_consumpt1$dateTime <- as.Date(strptime(hh_power_consumpt1$dateT, "%Y-%m-%dT%H:%M:%S"))
hh_power_consumpt1$dateTime <- as.Date(strptime(hh_power_consumpt1$dateT, "%d/%m/%YT%H:%M:%S"))
hh_power_consumpt1$dateTime <- as.Date(strptime(hh_power_consumpt1$dateT, "%d/%m/%Y %H:%M:%S"))
View(hh_power_consumpt1)
axis.POSIXct(1, hh_power_consumpt1$dateT, format="%m/%d %H:%M")
hh_power_consumpt1$sub_meter <- c(hh_power_consumpt1$Sub_metering_1)
dates <- seq(as.Date(hh_power_consumpt1$dateT, format="%d/%m/%Y") by = "days", length=length(sub_meter))
dates <- seq(as.Date(hh_power_consumpt1$dateT, format="%d/%m/%Y"), by="days", length=length(sub_meter))
dates <- seq(as.Date(hh_power_consumpt1$Date, format="%d/%m/%Y"), by="days", length=length(sub_meter))
dateIndex <- c(as.POSIXct(index(hh_power_consumpt1$dateT)))
?axis.Date
dow <- as.POSIXct(round(range(hh_power_consumpt1$dateT), "days"))
mday
times <- time(hh_power_consumpt1$dateT)
ticks <- seq(times[1], times[length(times)], by="days")
times <- time(hh_power_consumpt1$Sub_metering_1)
ticks <- seq(times[1], times[length(times)], by="days")
ticks <- seq(times[1], times[length(times)], by="weeks")
ticks <- seq(times[1], times[length(times)], by = "weeks")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_2, col="red")
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
box()
axis(1, at=1:2880, lab=c("Thu","Fri","Sat"))
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
max_range <- max(hh_power_consumpt1$Sub_metering_1)
axis(2, at=10*0:max_range)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
axis(1, lab=c("Thu","Fri","Sat"))
max_day = max(hh_power_consumpt1$dateT)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
axis(1, at=10*0:max_range)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
axis(1, at=10*0:max_range)
lines(hh_power_consumpt1$Sub_metering_2, col="red")
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l")
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
lines(hh_power_consumpt1$Sub_metering_2, col="red")
png(filename="C:/Users/m0banks/Documents/R/R-3.1.2/src/plot3_adv.png", height=480, width=480, bg="white")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", ann=FALSE)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
dev.off
dev.off()
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_2, col="red")
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, type="l", ann=FALSE, axes=FALSE)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, xaxt="n")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, xaxt="n", type="l", ann=FALSE)
axis.Date(1,at=hh_power_consumpt1$dateT,labels=format(hh_power_consumpt1$dateT, "%b-%d"),las=2)
lines(hh_power_consumpt1$Sub_metering_2, col="red")
axis.Date(1,at=hh_power_consumpt1$dateT,labels=format(hh_power_consumpt1$dateT, "%b-%d"),las=2)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, axes=FALSE, type="l", ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_2, col="red")
lines(hh_power_consumpt1$Sub_metering_2, col="red", type="l")
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
axis(1, at=1, lab=c("Thu"))
axis(1, at=10*0:max_range)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, axes=FALSE, type="l", ann=FALSE)
axis(1, at=10*0:max_range)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, axes=FALSE, type="l", ann=FALSE)
axis(1, at=10*0:max_range)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_2, col="red", axes=FALSE, type="l", ann=FALSE)
axis(1, at=10*0:max_range)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_2, col="red", axes=FALSE, type="l", ann=FALSE, ylim=(0,max_range))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_2, col="red", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
box()
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
axis(side=1)
axis(side=2)
axis(1, at=1:3, lab=c("Thu","Fri","Sat"))
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
dev.off()
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
axis.Date(side=1)
axis.Date(hh_power_consumpt1$dateT)
axis(1, hh_power_consumpt1$Date, format(hh_power_consumpt1$Date, "%b %d"), cex.axis=.7)
axis(1, hh_power_consumpt1$Date, format(hh_power_consumpt1$Date, "%b %d"))
drawTimeAxis(hh_power_consumpt1$dateT)
drawxAxis(hh_power_consumpt1$dateT)
?axis.Date
axis.Date(1, at=seq(as.Date(hh_power_consumpt1$dateT), max(hh_power_consumpt$dateT), "days"), labels=c("Thu","Fri","Sat"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT), max(hh_power_consumpt$dateT), "days"), labels=c("Thu","Fri","Sat"))
axis.Date(1, at = seq(as.Date("2001/1/1"), max(random.dates)+6, "days"),
labels = FALSE, tcl = -0.2)
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), max(hh_power_consumpt$dateT), "days"), labels=c("Thu","Fri","Sat"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt$dateT), "days"), labels=c("Thu","Fri","Sat"))
cc
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt$dateT)), "days"), labels=c("Thu","Fri","Sat"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), labels=c("Thu","Fri","Sat"))
axis(side=2)
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), labels=c("Thu","Fri","Sat"))
box()
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), labels=c("Thu","Fri","Sat"))
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
lines(hh_power_consumpt1$Sub_metering_2, col="red", type="l")
axis(side=1)
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), labels=c("Thu","Fri","Sat"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), labels=c("Thu","Fri","Sat"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"))
axis(side=1)
axis(side=1)
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
axis(side=2)
lines(hh_power_consumpt1$Sub_metering_2, col="red", type="l")
axis.POSIXct(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black",  type="l", ann=FALSE, ylim=c(0,max_range))
lines(hh_power_consumpt1$Sub_metering_2, col="red", type="l")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
axis.POSIXct(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), labels=c("Thu","Fri","Sat"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), labels=c("Thu","Fri","Sat"))
as.Date(min(hh_power_consumpt1$dateT))
as.Date(max(hh_power_consumpt1$dateT))
hh_power_consumpt2 <- hh_power_consumpt[ which(hh_power_consumpt$Date == "2/1/2007" | hh_power_consumpt$Date == "2/2/2007"), ]
as.Date(max(hh_power_consumpt2$dateT))
as.Date(max(hh_power_consumpt2$date))
as.Date(max(hh_power_consumpt2$Date))
hh_power_consumpt2$dateT <- as.POSIXct(paste(as.character(hh_power_consumpt2$Date), as.character(hh_power_consumpt2$Time)), format='%d/%m/%Y %H:%M:%S', tz="GMT")
as.Date(max(hh_power_consumpt2$dateT))
as.Date(min(hh_power_consumpt2$dateT))
plot(hh_power_consumpt2$dateT, hh_power_consumpt2$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
plot(hh_power_consumpt2$dateT, hh_power_consumpt2$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"), lab=c("Thu","Fri","Sat"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, ylim=c(0,max_range))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"))
lines(hh_power_consumpt1$Sub_metering_2, col="red", type="l")
axis(side=2)
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", type="l", ylab="Energy sub metering", ylim=c(0,max_range))
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
lines(hh_power_consumpt1$Sub_metering_3, col="blue")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_3, col="blue")
lines(hh_power_consumpt1$Sub_metering_3, col="blue")
axis(side=2)
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"))
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$Date)), as.Date(max(hh_power_consumpt1$Date)), "days"))
axis.Date(1, at=seq(as.Date(min(as.character(hh_power_consumpt1$Date)), as.Date(max(hh_power_consumpt1$Date)), "days"))
end
axis.Date(1, at=seq(as.Date(min(as.character(hh_power_consumpt1$Date))), as.Date(max(hh_power_consumpt1$Date)), "days"))
axis.Date(1, at=seq(as.Date(min(as.character(hh_power_consumpt1$Date))), as.Date(max(as.chararcter(hh_power_consumpt1$Date))), "days"))
axis.Date(1, at=seq(as.Date(min(as.character(hh_power_consumpt1$Date))), as.Date(max(as.character(hh_power_consumpt1$Date))), "days"))
max(as.character(hh_power_consumpt1$Date))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE)
axis.Date(1, at=seq(as.Date(min(as.character(hh_power_consumpt1$Date))), as.Date(max(as.character(hh_power_consumpt1$Date))), "days"))
axis.Date(1, at=seq(as.Date(min(as.character(hh_power_consumpt1$dateT))), as.Date(max(as.character(hh_power_consumpt1$dateT))), "days"))
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE, bty="n")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", type="l", ann=FALSE, bty="n")
lines(hh_power_consumpt1$Sub_metering_2, col="red", type="l")
box()
lines(hh_power_consumpt1$Sub_metering_2, col="red", type="l")
lines(hh_power_consumpt1$Sub_metering_2, col="red")
lines(hh_power_consumpt1$Sub_metering_2, col="red", lty=1)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red", lty=1)
lines(hh_power_consumpt1$Sub_metering_2, type="l")
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", type="l", ann=FALSE, bty="n")
box()
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", axes=FALSE, type="l", ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", type="l", ann=FALSE, bty="n")
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
box()
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", type="l", ylab="Energy sub meeting", ann=FALSE, bty="n")
box()
lines(hh_power_consumpt1$Sub_metering_3, col="blue", ylab="Energy sub metering")
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_3, col="blue", type="l", xlab="", ylab="Energy sub meeting", ann=FALSE, bty="n")
axis(side=2)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_3, col="blue", type="l", ann=FALSE, bty="n")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_2, col="red", type="l", ann=FALSE, bty="n")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_3, col="blue", type="l", ann=FALSE, bty="n", yaxt="n")
axis(1, at=10*0:max_range)
axis(2, at=10*0:max_range)
box()
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
lines(hh_power_consumpt1$Sub_metering_3, type="l", col="black")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", type="l", ann=FALSE, bty="n", yaxt="n")
axis(side=2)
box()
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
library(datasets)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1, col="black", type="l", ann=FALSE, bty="n", yaxt="n")
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(x)
plot(hh_power_consumpt1$Sub_metering_1)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(hh_power_consumpt1$dateT)
plot(hh_power_consumpt1$dateT, hh_power_consumpt1$Sub_metering_1)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
plot(hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
lines(hh_power_consumpt1$Sub_metering_3, type="l", col="blue")
axis(side=2)
axis.Date(1, at=seq(as.Date(min(hh_power_consumpt1$dateT)), as.Date(max(hh_power_consumpt1$dateT)), "days"))
title(ylab="Energy sub metering")
box()
legend(1,max_range,names(hh_power_consumpt1),col=plot_colors, lty=1:3)
plot_colors <- c("black","red","blue")
legend(1,max_range,names(hh_power_consumpt1),col=plot_colors, lty=1:3)
?names
legend(1,max_range,names[8:10],col=plot_colors, lty=1:3)
legend(1,max_range,names(hh_power_consumpt1)[8:10],col=plot_colors, lty=1:3)
legend(1,max_range,names(hh_power_consumpt1)[8:10],col=plot_colors)
legend(1,max_range,names(hh_power_consumpt1)[8:10],col=plot_colors, lty=1)
legend(1,max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1)
legend(4,max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1)
legend(3,max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1)
legend(2,max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1)
legend(1,max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1)
?legend
legend(1,max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1, xjust=1)
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1, xjust=1)
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1, xjust=0)
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1, xjust=-1)
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1)
plot(hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
lines(hh_power_consumpt1$Sub_metering_3, type="l", col="blue")
axis(side=2)
title(ylab="Energy sub metering")
box()
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1)
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1, xjust=-1)
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1, xjust=1)
plot(hh_power_consumpt1$Sub_metering_1, type="l", axes=FALSE, ann=FALSE)
lines(hh_power_consumpt1$Sub_metering_2, type="l", col="red")
lines(hh_power_consumpt1$Sub_metering_3, type="l", col="blue")
axis(side=2)
box()
legend(max(times),max_range,names(hh_power_consumpt1)[7:9],col=plot_colors, lty=1, xjust=1)
title(ylab="Energy sub metering")
savehistory("~/R/R-3.1.2/src/Global_Active_Power2/plot3.R")
